recommendations = [
  # @config-manager:start python
  'eeyore.yapf',
  'littlefoxteam.vscode-python-test-adapter',
  'ms-python.python',
  'njpwerner.autodocstring',
  'thebutlah.reorder-python-imports',
  'zuban.zubanls',
  # @config-manager:end python
]
