recommendations = [
  # @config-manager:start standard
  '1Password.op-vscode',
  'albymor.increment-selection',
  'anchoreinc.grype-vscode',
  'annsk.alignment',
  'aquasecurityofficial.trivy-vulnerability-scanner',
  'arr.marksman',
  'bierner.markdown-checkbox',
  'bierner.markdown-preview-github-styles',
  'bierner.markdown-yaml-preamble',
  'chouzz.vscode-better-align',
  'christian-kohler.path-intellisense',
  'claui.email-addresses',
  'cmacu.gotoanything',
  'codezombiech.gitignore',
  'DavidWang.ini-for-vscode',
  'eamodio.gitlens',
  'editorconfig.editorconfig',
  'emeraldwalk.runonsave',
  'esbenp.prettier-vscode',
  'fcrespo82.markdown-table-formatter',
  'fnando.linter',
  'foxundermoon.shell-format',
  'geeebe.duplicate',
  'gurumukhi.selected-lines-count',
  'hbenl.vscode-test-explorer',
  'jq-syntax-highlighting.jq-syntax-highlighting',
  'kevinkyang.auto-comment-blocks',
  'lamartire.git-indicators',
  'mads-hartmann.bash-ide-vscode',
  'melt-inc.yamlfmt-vscode',
  'mohsen1.prettify-json',
  'ms-vscode-remote.remote-containers',
  'ms-vscode.test-adapter-converter',
  'nhoizey.gremlins',
  'oliversturm.fix-json',
  'quicktype.quicktype',
  'redhat.vscode-yaml',
  'rogalmic.bash-debug',
  'rvben.rumdl',
  'sidneys1.gitconfig',
  'stkb.rewrap',
  'tamasfe.even-better-toml',
  'timonwong.shellcheck',
  'tomoki1207.pdf',
  'tyriar.sort-lines',
  'usernamehw.errorlens',
  'visualstudioexptteam.vscodeintellicode',
  'vivaxy.vscode-conventional-commits',
  'yzhang.markdown-all-in-one',
  'zardoy.fix-all-json',
  # @config-manager:end standard
]
